services:
  db:
    image: mysql:8.0-oracle
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb_db:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "23017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mysql_data:
  mongodb_data:
